var express = require('express');
var router = express.Router();
var controller = require('../controllers/POSController');
router.post('/createStock', controller.createStock);
router.post('/updateStock', controller.updateStock);
router.post('/inquiryStock', controller.inquiryStock);
router.post('/inquiryListStock', controller.inquiryListStock);
router.post('/buyItem', controller.buyItem);
router.post('/inquiryTransaction', controller.inquiryTransaction);
router.post('/uploadImage', controller.uploadImage);
module.exports = router;